import { CommissionHistoryEntry, CommissionRangeRow } from "@/types/commission";
import { createRowId } from "@/lib/commission/utils";

export const MOCK_RETAILERS = [
  { id: "ret_001", name: "Sharma Digital Store", code: "RTL001" },
  { id: "ret_002", name: "Gupta Mobile Shop", code: "RTL002" },
  { id: "ret_003", name: "Patel FinServe", code: "RTL003" },
];

export const MOCK_DISTRIBUTORS = [
  { id: "dist_001", name: "North Zone Distributors", code: "DST001" },
  { id: "dist_002", name: "Metro Pay Network", code: "DST002" },
];

export const MOCK_MASTER_DISTRIBUTORS = [
  { id: "md_001", name: "PayTrue Master North", code: "MD001" },
  { id: "md_002", name: "PayTrue Master West", code: "MD002" },
];

function baseRow(
  partial: Omit<CommissionRangeRow, "id"> & { id?: string }
): CommissionRangeRow {
  return { id: partial.id ?? createRowId(), ...partial };
}

export const MOCK_COMMISSION_ROWS: CommissionRangeRow[] = [
  baseRow({
    serviceId: "dmt",
    serviceName: "DMT",
    scope: "global",
    rangeFrom: 1,
    rangeTo: 1000,
    deductionType: "flat",
    deductionValue: 10,
    retailerCommissionType: "flat",
    retailerCommission: 5,
    distributorCommissionType: "flat",
    distributorCommission: 2,
    masterDistributorCommissionType: "flat",
    masterDistributorCommission: 1,
    companyMarginType: "flat",
    companyMargin: 2,
    priority: 1,
    status: "active",
  }),
  baseRow({
    serviceId: "dmt",
    serviceName: "DMT",
    scope: "global",
    rangeFrom: 1001,
    rangeTo: 5000,
    deductionType: "flat",
    deductionValue: 15,
    retailerCommissionType: "flat",
    retailerCommission: 8,
    distributorCommissionType: "flat",
    distributorCommission: 3,
    masterDistributorCommissionType: "flat",
    masterDistributorCommission: 2,
    companyMarginType: "flat",
    companyMargin: 2,
    priority: 2,
    status: "active",
  }),
  baseRow({
    serviceId: "dmt",
    serviceName: "DMT",
    scope: "global",
    rangeFrom: 5001,
    rangeTo: 10000,
    deductionType: "flat",
    deductionValue: 20,
    retailerCommissionType: "flat",
    retailerCommission: 10,
    distributorCommissionType: "flat",
    distributorCommission: 4,
    masterDistributorCommissionType: "flat",
    masterDistributorCommission: 2,
    companyMarginType: "flat",
    companyMargin: 4,
    priority: 3,
    status: "active",
  }),
  baseRow({
    serviceId: "aeps_cw",
    serviceName: "AEPS Cash Withdrawal",
    scope: "global",
    rangeFrom: 1,
    rangeTo: 1000,
    deductionType: "percentage",
    deductionValue: 0.8,
    retailerCommissionType: "percentage",
    retailerCommission: 0.5,
    distributorCommissionType: "percentage",
    distributorCommission: 0.2,
    masterDistributorCommissionType: "percentage",
    masterDistributorCommission: 0.1,
    companyMarginType: "percentage",
    companyMargin: 0,
    priority: 1,
    status: "active",
  }),
  baseRow({
    serviceId: "aeps_cw",
    serviceName: "AEPS Cash Withdrawal",
    scope: "global",
    rangeFrom: 1001,
    rangeTo: 5000,
    deductionType: "percentage",
    deductionValue: 0.7,
    retailerCommissionType: "percentage",
    retailerCommission: 0.45,
    distributorCommissionType: "percentage",
    distributorCommission: 0.15,
    masterDistributorCommissionType: "percentage",
    masterDistributorCommission: 0.1,
    companyMarginType: "percentage",
    companyMargin: 0,
    priority: 2,
    status: "active",
  }),
  baseRow({
    serviceId: "upi",
    serviceName: "UPI",
    scope: "retailer",
    retailerId: "ret_001",
    retailerName: "Sharma Digital Store",
    rangeFrom: 1,
    rangeTo: 25000,
    deductionType: "flat",
    deductionValue: 2,
    retailerCommissionType: "flat",
    retailerCommission: 1,
    distributorCommissionType: "flat",
    distributorCommission: 0.5,
    masterDistributorCommissionType: "flat",
    masterDistributorCommission: 0.25,
    companyMarginType: "flat",
    companyMargin: 0.25,
    priority: 1,
    status: "active",
  }),
  baseRow({
    serviceId: "bbps",
    serviceName: "BBPS",
    scope: "distributor",
    distributorId: "dist_001",
    distributorName: "North Zone Distributors",
    rangeFrom: 1,
    rangeTo: 50000,
    deductionType: "percentage",
    deductionValue: 1.2,
    retailerCommissionType: "percentage",
    retailerCommission: 0.8,
    distributorCommissionType: "percentage",
    distributorCommission: 0.25,
    masterDistributorCommissionType: "percentage",
    masterDistributorCommission: 0.1,
    companyMarginType: "percentage",
    companyMargin: 0.05,
    priority: 1,
    status: "inactive",
  }),
];

export const MOCK_COMMISSION_HISTORY: CommissionHistoryEntry[] = [
  {
    id: "hist_001",
    commissionId: MOCK_COMMISSION_ROWS[0].id,
    field: "Retailer Commission",
    oldValue: "₹4",
    newValue: "₹5",
    updatedBy: "Admin",
    updatedAt: "2026-06-28T10:30:00Z",
  },
  {
    id: "hist_002",
    commissionId: MOCK_COMMISSION_ROWS[0].id,
    field: "Deduction Value",
    oldValue: "₹8",
    newValue: "₹10",
    updatedBy: "Admin",
    updatedAt: "2026-06-27T14:15:00Z",
  },
  {
    id: "hist_003",
    commissionId: MOCK_COMMISSION_ROWS[3].id,
    field: "Status",
    oldValue: "Inactive",
    newValue: "Active",
    updatedBy: "Admin",
    updatedAt: "2026-06-25T09:00:00Z",
  },
];
