"use client";

import { useEffect, useState } from "react";
import { useRoleAccess } from "@/hooks/useAuth";
import { useAppDispatch, useAppSelector } from "@/hooks/useAppStore";
import { fetchAdminBusinessReport } from "@/store/api/adminModuleApi";
import { selectAdminBusinessReport } from "@/store/selectors/adminSelectors";
import { Card, CardHeader } from "@/components/common/Card";
import { StatCard } from "@/components/cards/StatCard";
import { Input } from "@/components/common/Input";
import { Button } from "@/components/common/Button";
import { PageHeader } from "@/components/common/PageHeader";
import { GRADIENT_CARDS } from "@/constants";
import { formatCurrency } from "@/lib/utils";
import { fetchWalletHistory } from "@/store/api/superAdminWalletApi";

function reportValue(
  report: ReturnType<typeof selectAdminBusinessReport>,
  keys: string[]
): number {
  if (!report) return 0;
  for (const key of keys) {
    const val = report[key];
    if (typeof val === "number") return val;
  }
  return 0;
}

export default function ReportsPage() {
  const dispatch = useAppDispatch();
  const { isAdminApiAuth, isSuperAdminApiAuth } = useRoleAccess();
  const report = useAppSelector(selectAdminBusinessReport);
  const { isLoadingBusinessReport, error } = useAppSelector(
    (state) => state.adminModule
  );
  const { history, isLoadingHistory } = useAppSelector(
    (state) => state.superAdminWallet
  );
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");

  const loadReport = () => {
    dispatch(
      fetchAdminBusinessReport({
        startDate: startDate || undefined,
        endDate: endDate || undefined,
      })
    );
  };

  useEffect(() => {
    if (isAdminApiAuth) {
      loadReport();
    }
    if (isSuperAdminApiAuth) {
      dispatch(fetchWalletHistory({ page: 1, pageSize: 100 }));
    }
  }, [dispatch, isAdminApiAuth, isSuperAdminApiAuth]);

  if (isAdminApiAuth) {
    const cards = [
      {
        title: "Master Distributor Business",
        value: formatCurrency(
          reportValue(report, ["masterDistributorBusiness"])
        ),
      },
      {
        title: "Distributor Business",
        value: formatCurrency(reportValue(report, ["distributorBusiness"])),
      },
      {
        title: "Retailer Business",
        value: formatCurrency(reportValue(report, ["retailerBusiness"])),
      },
      {
        title: "Today's Business",
        value: formatCurrency(
          reportValue(report, ["todaysBusiness", "todayBusiness"])
        ),
      },
      {
        title: "Monthly Business",
        value: formatCurrency(reportValue(report, ["monthlyBusiness"])),
      },
      {
        title: "Total Business",
        value: formatCurrency(reportValue(report, ["totalBusiness"])),
      },
    ];

    return (
      <div className="page-container space-y-6">
        <PageHeader
          breadcrumb="Admin"
          title="Business Report"
          subtitle="Business generated by users under your hierarchy"
        />
        {error && (
          <div className="rounded-xl border border-accent-red/30 bg-accent-red/10 px-4 py-3 text-sm text-accent-red">
            {error}
          </div>
        )}
        <Card>
          <CardHeader title="Date Filter" />
          <div className="grid gap-4 sm:grid-cols-3">
            <Input
              label="Start Date"
              type="date"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
            />
            <Input
              label="End Date"
              type="date"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
            />
            <div className="flex items-end">
              <Button onClick={loadReport} isLoading={isLoadingBusinessReport}>
                Apply Filter
              </Button>
            </div>
          </div>
        </Card>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {cards.map((card, index) => (
            <StatCard
              key={card.title}
              title={card.title}
              value={isLoadingBusinessReport ? "..." : card.value}
              gradient={`bg-gradient-to-br ${GRADIENT_CARDS[index % GRADIENT_CARDS.length]}`}
            />
          ))}
        </div>
      </div>
    );
  }

  if (isSuperAdminApiAuth) {
    return (
      <div className="space-y-6">
        <PageHeader title="Reports" subtitle="Super admin wallet reports" />
        <div className="grid gap-4 sm:grid-cols-3">
          <Card>
            <p className="text-sm text-muted">Total Transactions</p>
            <p className="text-2xl font-bold">{history.length}</p>
          </Card>
          <Card>
            <p className="text-sm text-muted">Loading</p>
            <p className="text-2xl font-bold">{isLoadingHistory ? "..." : "Live"}</p>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="page-container">
      <PageHeader title="Reports" subtitle="Business and transaction reports" />
      <Card>
        <CardHeader title="Sign in required" subtitle="Reports are available after login" />
      </Card>
    </div>
  );
}
